# Generated by Django 2.2.3 on 2019-07-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='description',
        ),
    ]
